version: "3.8"

services:
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../backend
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=fdafeinfxdfewf4232rtg
      - MONGO_URI=mongodb+srv://movie-review-app:f3CP0vU9GyZnxxh4@cluster0.knrrwt7.mongodb.net/movieReviewApp?retryWrites=true&w=majority
      - CLOUD_API_SECRET=tjmI3NQDFz2JCgJMCKlug92qcHY
      - CLOUD_API_KEY=851412362268586
      - CLOUD_NAME=dzociog2r
      - MAIL_TRAP_USER=fdab8446217979
      - MAIL_TRAP_PASS=746d901816952f
      - OFFICIAL_EMAIL=hello@linze.me
      - RESET_PASSWORD_URL=https://linze.me

  frontend:
    restart: always
    environment:
      - VITE_BASE_URL=/api
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
