version: '3.8'

services:
  nginx:
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    # ports:
    #   - "3050:80"

  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../backend
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=fdafeinfxdfewf4232rtg
      - MONGO_URI=mongodb+srv://movie-review-app:f3CP0vU9GyZnxxh4@cluster0.knrrwt7.mongodb.net/movieReviewApp?retryWrites=true&w=majority
      - CLOUD_API_SECRET=tjmI3NQDFz2JCgJMCKlug92qcHY
      - CLOUD_API_KEY=851412362268586
      - CLOUD_NAME=dzociog2r
      - BREVO_API_KEY=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
      - OFFICIAL_EMAIL=hello@linze.me
      - RESET_PASSWORD_URL=https://linze.me

  # frontend:
  #   environment:
  #     - VITE_BASE_URL=/api
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./frontend
  #   volumes:
  #     - /app/node_modules
  #     - ./frontend:/app