services:
  mongodb:
    restart: always
    image: mongo:7.0-jammy
    container_name: moviefy-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - moviefy_network

  backend:
    build: ./backend
    container_name: moviefy-backend
    command: npm run dev
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    # CORRECTED: Map to the port the backend is actually using
      - ./backend/uploads:/app/uploads
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - moviefy_network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: moviefy-frontend
    command: npm run dev
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - moviefy_network
    depends_on:
      - backend

    # ADDED: MailHog service to catch all outgoing emails
  mailhog:
    image: mailhog/mailhog
    container_name: moviefy-mailhog
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
    networks:
      - moviefy_network

volumes:
  mongo_data:

networks:
  moviefy_network:
    driver: bridge